### ISSUE TITLE
Using Facebook Ads on Right To Know Day

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/alaveteli-experiments#100]
## Q: Will advertising Right To Know Day / Alaveteli sites using Facebook Ads in the UK, Australia, Hungary, Ukraine, Europe, Czech Republic and Croatia bring people to the site? Will these people then go on to make requests?

How do differently worded Facebook ads compare? I.e. do ads including figures increase likelihood of people making a request? Eventually, we could then run ads on 'normal' days (i.e. not Right To Know Day) and see how click throughs/conversions compare. Hopefully, we can then answer the question 'Does advertising on a special day bring more people to sites?'

[Explain how you will measure this]

We will track how many people clicked on Facebook ads to come to the site. We will also track how many requests were made from the Facebook ad traffic. 

[What do we need to do to be able to take the measurements?]

We would need to make sure that urls in Facebook ads have tracking params in them, and that Alaveteli sites' Google Analytics all have goal conversions set up, so new requests can be tracked.

**Comment by Gemmamysoc** [comment]
Bec from mySociety research team is interested in helping with this

**Comment by garethrees** [comment]
Can use the [Google URL builder](https://support.google.com/analytics/answer/1033867?hl=en) to create the tracking links. We have [some guidelines](https://wiki.mysociety.org/wiki/Google_Analytics) on what to name these.

**Comment by Gemmamysoc** [comment]
Copy for experiment ideas: https://docs.google.com/document/d/1ExQmheWs7cd21eVIBD5rvM7bicNS38V2BwwuYk2s3eY/edit

**Comment by Gemmamysoc** [comment]
Here are initial results from experiment: https://docs.google.com/document/d/1l7RY2WDuh5Sn4G_J-672FHlGlFxqEIm7zxzUcNRUTGk/edit 

I will write up in a way that is easier to compare results form all sites.

**Comment by Gemmamysoc** [comment]
Write up of results here: https://github.com/mysociety/alaveteli-experiments/blob/master/experiments/using-facebook-advertising-right-to-know-day.md

**Comment by Gemmamysoc** [comment]
See if Uganda's increased, sustained level of usage continues. Try and find out if it can be attributed to the Facebook ads

**Comment by Gemmamysoc** [comment]
Ugandan site traffic has continued at a higher, more sustained level of usage

**Comment by garethrees** [comment]
Awesome news!

**Comment by Gemmamysoc** [comment]
Trying to figure out if that is directly attributable to the Facebook ads, or if there were other factors

**Comment by garethrees** [comment]
Suggested a retreat session on this

**Comment by garethrees** [comment]
Oops, we have a writeup https://github.com/mysociety/alaveteli-experiments/blob/master/experiments/using-facebook-advertising-right-to-know-day.md. Going to discuss this at the 2016 retreat, so closing unless any other actions come out of that discussion.

Again, a big thanks to @Gemmamysoc for all the work on this one! 🍰
