### ISSUE TITLE
How long did it take for WDTK to hit target level?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#105]
Not sure if we can get this out of projectDB?

Worth knowing as a benchmark.

**Comment by dracos** [comment]
Launched mid December 2007; hit target (and never dropped below thereafter) 26th August 2008.
This SQL isn't very nice or fast, but I didn't want to spend time getting my head around an appropriate window function:
```
foi=# select date,
    (select count(*) from info_requests
        where created_at>=date-'6 months'::interval and created_at<date) as c
from
(select generate_series('2007-10-01'::timestamp, '2016-10-01'::timestamp, '1 day') as date) dates;
```

**Comment by garethrees** [comment]
Related https://github.com/mysociety/research/issues/54

**Comment by garethrees** [comment]
What is target-hitting?

> A deployment that receives either at least 125,000 sessions in any rolling six month period in the target year or facilitates at least 2,500 transactions in any rolling six month period in the target time period.
