### ISSUE TITLE
Does placement of donation button change donation click-through?

### ISSUE THREAD

**Issue by ajparsons** [mysociety/alaveteli-experiments#115]
## Q: Does moving the donation link from the sidebar to the footer (swapping with the AsktheEU link) on the request display page increases click through to the donation page. 

We will measure this with via an A/B test in google analytics. Campaigns will be marked up to track conversion value.

**Comment by wrightmartin** [comment]
Some explorations about how this may look with a visual change and without one

![desktop hd copy 2](https://user-images.githubusercontent.com/2292925/50165144-319dda00-02dc-11e9-8f13-863c8db4476f.png)
![desktop hd copy](https://user-images.githubusercontent.com/2292925/50165159-3cf10580-02dc-11e9-9ac8-d606f5c2b554.png)

**Comment by wrightmartin** [comment]
We'll add a parameter to the UTM tags based on which variant of the experiment people have clicked the donate button for

`:utm_content => 'experiment_no_0',` will be as is now, with the donate button in the sidebar on the right
`:utm_content => 'experiment_no_1',` will be the switched version with the donate button positioned at the bottom of the page

**Comment by ajparsons** [comment]
On the utm content, I meant (but did not actually say clearly anywhere) that we should include the alaveteli experiment issue number in the content as the number. For the first experiment we can leave as is, but when we switch in future we should adjust the content so future experiments have a distinct content.

**Comment by wrightmartin** [comment]
ah - we're pulling it directly from Google's own `cxApi.chooseVariation` in this case

**Comment by ajparsons** [comment]
The result of this was yes, conversions to the donate page were about twice as high.
