### ISSUE TITLE
Create a blog post of best requests that have been picked up by media/had impact

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#18]
## Q: Can we grow the sites via inbound links?

[Explain how you will measure this]

Increase in traffic from links in blog post

[What do we need to do to be able to take the measurements?]
- [x] Ask gold level partners for their best requests on our catchup calls [Google Doc](https://docs.google.com/spreadsheets/d/1Qo5Ag5CJeqeF1sL0Pa2NSd9IrB9QeW8Jty5aPaAGW9k/edit#gid=0)
- [x] Part 1: https://www.mysociety.org/2016/05/19/stories-of-alaveteli-what-has-been-revealed-through-freedom-of-information-sites-around-the-world-part-1/
- [x] Part 2: https://www.mysociety.org/2016/05/31/stories-of-alaveteli-what-has-been-revealed-through-foi-sites-around-the-world-part-2/
- [x] Part 3 https://www.mysociety.org/2016/07/07/stories-of-alaveteli-what-has-been-revealed-through-foi-sites-around-the-world-part-3/
- [x] Part 4 https://www.mysociety.org/2016/08/08/stories-of-alaveteli-what-has-been-revealed-through-foi-sites-around-the-world-part-4/
- [x] Part 5 https://www.mysociety.org/2016/08/24/stories-of-alaveteli-what-has-been-revealed-through-foi-sites-around-the-world-part-5/
- [x] For Right To Know Day on 28th Sept, make Summary blog post, collating each story
- [x] Make list of other FOI Networks
- [x] Share with other FOI Networks
- [ ] Measure traffic coming from links in blog post

**Comment by garethrees** [comment]
- https://www.mysociety.org/2016/05/19/stories-of-alaveteli-what-has-been-revealed-through-freedom-of-information-sites-around-the-world-part-1/
- https://www.mysociety.org/2016/05/31/stories-of-alaveteli-what-has-been-revealed-through-foi-sites-around-the-world-part-2/

**Comment by garethrees** [comment]
@Gemmamysoc how many more of these have we got so far?

**Comment by Gemmamysoc** [comment]
I've got Part 3, which I hope to publish today. And enough material for another two blog posts. I'd like to   then collate these, and perhaps share the whole series with other FOI Networks.

**Comment by garethrees** [comment]
Awesome, thanks. I've updated the TODO list to reflect where we are.

**Comment by garethrees** [comment]
Worth sending the summary to http://freedominfo.org?

**Comment by Gemmamysoc** [comment]
Results: 

This series of blog posts bought the following amount of sessions/new users to these Alaveteli sites: 

Dostup Pravda: 13 sessions and 3 new users.
AsktheEU: 4 sessions
RightToKnow: 5 sessions and 5 new users
KiMiTud: 0 sessions and 0 new users :(
