### ISSUE TITLE
Interview Francis Irving about first years of site

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#20]
## Q: What factors caused WDTK to grow?

Unmeasurable, but very insights will be valuable

**Comment by Gemmamysoc** [comment]
Questions I could ask:

- What activities did you conduct to promote the site when it first launched? 
- Why do you think WhatDoTheyKnow grew so rapidly? Can you attribute the growth of WDTK to any particular promotional activity?

Any other ideas?

**Comment by garethrees** [comment]
This has found its way in to the current sprint.

**Comment by Gemmamysoc** [comment]
Notes from interview are here: https://docs.google.com/document/d/16sUvKLLi6RnFYCjh1UryXuZK-lic5O-4kRkqxdkBz6w/edit#

**Comment by garethrees** [comment]
Actually we should write this up – just dump the summary in to a new file here.
