### ISSUE TITLE
Are the widgets effective in growing the site?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#28]
## Q: Are the widgets effective in growing the site?

[Explain how you will measure this]

Proportion of traffic to site that comes from widgets

[What do we need to do to be able to take the measurements?]
- [x] Add analytics to widgets
- [x] Measure transactions from widgets (`WidgetVote.count` ?)
- [ ] <strike>Measure traffic from widgets (analytics events)</strike>

**Comment by Gemmamysoc** [comment]
News from Transparencia.be: Between 22 Sept 2016 and 25 Oct 2017 96.26% of all sessions and 91.47% of all new users on Transparencia have come from the widgets on this site: http://nassogne.blogs.sudinfo.be/ Pretty impressive!
