### ISSUE TITLE
Does an automatically generated list of recent successful requests result in more people clicking on the start of the 'make a request' funnel than a curated set of 'top requests'?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#43]
## Q: Does an automatically generated list of recent successful requests result in more people clicking on the start of the 'make a request' funnel than a curated set of 'top requests'?

[Explain how you will measure this]

Measure change in conversion funnel

[What do we need to do to be able to take the measurements?]

Make version of front page that uses list of successful requests  - A/B test in google. Make sure funnel is defined in google analytics

**Comment by garethrees** [comment]
Current progress:

![screen shot 2016-07-04 at 12 43 21](https://cloud.githubusercontent.com/assets/282788/16559447/e82e0c9c-41e4-11e6-9e28-875a899d7c84.png)

How long are we going to leave this run for?

**Comment by lizconlan** [comment]
Nick says that there's no harm in leaving it running until Analytics declares a winner, but...

![screen shot 2016-07-18 at 12 27 29](https://cloud.githubusercontent.com/assets/27760/16913544/18c5367e-4ce3-11e6-8029-93403c13909e.png)
 
...as we've run it for 60 days+ with no clear winner we could equally say that it's not making a significant difference and shut it down ourselves.

We could even consider re-running it once we've got [#3360](https://github.com/mysociety/alaveteli/issues/3360) sorted out

**Comment by garethrees** [comment]
Personally I'd say the answer to this question is pretty much "it makes no noticeable difference".

This doesn't really surprise me, given that we know the homepage isn't viewed by a large proportion of visitors.

**Comment by lizconlan** [comment]
Experiment stopped, moving it to needs-writeup

**Comment by lizconlan** [comment]
(we could take out the experiment-specific code on the page at this point if we wanted)

**Comment by garethrees** [comment]
- [x] Stop experiment
- [ ] Write up
- [ ] Remove experiment code
