### ISSUE TITLE
Can we drive traffic from WDTK to AskTheEU?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#50]
## Q: Can we drive traffic from WDTK to AskTheEU?

[Explain how you will measure this]

Look at referrals from WDTK

[What do we need to do to be able to take the measurements?]

- [x] Advertise AskTheEU on front page of WDTK
- [x] measure referrals from these links to AsktheEU

**Comment by Gemmamysoc** [comment]
Extra stat to add to the above: Out of the 422 sessions, 139 requests were made - a 33.10% goal conversion rate

**Comment by Gemmamysoc** [comment]
That's the highest goal conversion rate of any traffic source!

**Comment by garethrees** [comment]
So I think the _answer_ here is yes we can, and it had good results for AskTheEU.

Moving this to "needs writeup"

**Comment by Gemmamysoc** [comment]
"Perhaps now we put similar banners on other EU sites?" -regarding this - it probably doesn't make sense to advertise AsktheEU on Italian, Croatian, Hungarian and Czech instances, as AsktheEU is only in French, English, Spanish and soon to be German.

**Comment by garethrees** [comment]
They can still _ask_ in one of the "official" EU languages AFAIK. They just need to be able to navigate the site in one of the available languages, which shouldn't be too difficult given that they should be familiar with their national install.

**Comment by Gemmamysoc** [comment]
That's true. I have created a new ticket for this anyway: https://github.com/mysociety/alaveteli-experiments/issues/91

**Comment by Gemmamysoc** [comment]
Ah, sorry. Didn't add this vital bit of info:

Out of the 422 sessions, 342 of them were from clicking on advert/banner on Request pages, 46 from the [Find an Authority](https://www.whatdotheyknow.com/select_authority) page, and 34 were from homepage. 

So placing it on the request pages if the most effective location.
