### ISSUE TITLE
How much traffic comes from Adwords to http://kimittud.atlatszo.hu/?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#60]
Q: How much traffic comes from Adwords to http://kimittud.atlatszo.hu/?

[Explain how you will measure this]

Look in analytics

**Comment by Gemmamysoc** [comment]
Just having a look at recent data. Between 20th March 2016 to 18th July 2016, the Adwords are now bringing 14.53% of all sessions to the site, and 16.65% of new users! So has pretty much tripled since my comment above :) The conversion rate is only 0.12% though, which is the lowest of all traffic channels. It also has the highest bounce rate of all traffic sources.

**Comment by skylark1848** [comment]
What are generally the reasons for high bounce rates? People just don't find what they expected?

**Comment by Gemmamysoc** [comment]
A high bounce rate on Alavateli sites isn't necessarily a bad thing. Lots of people who visit are browsers looking for a certain bit of information. They click onto a request page, get the information they need from that page without having to click on anything, and leave.  It would be good to dig into this further - e.g. do requests that have the response clearly on the page (not on an attachment) have a higher bounce than requests where the user has to click on an attachment to view the response? 

Of course a high bounce rate can also be a bad thing - people might be coming and not finding the information they need, and the site doesn't interest/engage them enough to interact with it any more.

**Comment by Gemmamysoc** [comment]
Have looked again at this. Between 20 March 2016 and 27 September 2016 25.54% of all traffic to KiMitTud came from Adwords. That's the second biggest source of traffic after Organic Search. That's 18,499 sessions and 15,151 new users. The bounce rate is no longer the highest of all traffic sources. The conversion rate (of people making a request) is still the lowest of all traffic sources though - 0.05% - only 10 requests in total.
