### ISSUE TITLE
Do prominent donation banners increase donations?

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli-experiments#98]
We've added donate CTAs in the sidebar and request sent message on WDTK. Have these increased donation conversions?
- https://github.com/mysociety/whatdotheyknow-theme/issues/309
- https://github.com/mysociety/internal/issues/11
- https://github.com/mysociety/whatdotheyknow-theme/pull/318
- https://github.com/mysociety/whatdotheyknow-theme/pull/320

Not sure what analytics we have around this area, so will need some input from @jacksonj04.

**Comment by garethrees** [comment]
https://dl.dropboxusercontent.com/u/7452806/donations.png

**Comment by garethrees** [comment]
@abimysoc how much are we able to break down that increase by site?

**Comment by abimysoc** [comment]
@zarino set up [this Analytics dashboard](https://analytics.google.com/analytics/web/#dashboard/2Qjlj4koQJO3fU1LZAjyUw/a660910w61534424p63017268/) to show visits to the /donate page by site. 

That's not tracking _completions_ (i.e. whether those visitors then go on to give us money). There was some email discussion in July about this in which we identified what the completion page was (https://secure.mysociety.org/donate/thanks), but I don't think any further progress was made, I certainly haven't got the Analytics skills to do it...

**Comment by garethrees** [comment]
Yes https://github.com/mysociety/whatdotheyknow-theme/issues/284#issuecomment-270660421
